fail if plugin returns no output

diff --git a/tools/test b/tools/test
--- a/tools/test
+++ b/tools/test
@@ -17,7 +17,14 @@ NC='\033[0m' # No Color
 for i in "$@"; do
     OUTPUT=$($i)
     EXPECTED_OUTPUT_FILE=tests/outputs/$(basename $i)
+
     echo -e "${YELLOW}[INFO] validating $i..."
+
+    if [[ -z "$OUTPUT" ]]; then
+      echo -e "${RED}[FAILED]: plugin returned no output $i."
+      exit 1
+    fi
+
     if [[ -f "$EXPECTED_OUTPUT_FILE" ]]; then
       diff --color=always -u $EXPECTED_OUTPUT_FILE <(cat<<<"$OUTPUT")
       if [[ "$?" != "0" ]]; then
